// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgbbmbgghwnzozlmluuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnYmJtYmdnaHduem96bG1sdXV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTAxNjAsImV4cCI6MjA3MTI2NjE2MH0.M6V4UjNfVeZbsiXQ8xeGOgopZZ2OCBFxjpPBw2OkSls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});